mod 'puppetlabs/apt',        '7.6.0'
mod 'puppetlabs/docker',     '3.12.0'
mod 'puppetlabs/powershell', '3.0.1'
mod 'puppetlabs/pwshlib',    '0.5.1'
mod 'puppetlabs/reboot',     '2.4.0'
mod 'puppetlabs/stdlib',     '6.5.0'
mod 'puppetlabs/translate',  '2.2.0'
mod 'puppetlabs-docker', '3.12.0'
